[workspace]
resolver = "2"
members = ["src/*"]

[workspace.dependencies]
anyhow = "1.0.70"
serde = "1.0.159"
serde_json = "1.0.95"
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "uuid", "json", "chrono", "sqlite", "offline", "migrate"] }
tokio = { version = "1.27.0", features = ["full"] }
