[workspace]
resolver = "2"
members = ["src/*"]

[workspace.dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
fake = { version = "2.6.0", features = ["derive", "chrono", "serde_json"] }
lazy_static = "1.4.0"
minijinja = "0.32.1"
rand = "0.8"
regex = "1.8.4"
serde = "1.0.164"
serde_json = "1.0.99"
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "uuid", "json", "chrono", "sqlite", "offline", "migrate"] }
tokio = { version = "1.28.2", features = ["full"] }
