[workspace]
resolver = "2"
members = ["src/*"]

[workspace.dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
chrono = "0.4.31"
fake = { version = "2.8.0", features = ["derive", "chrono", "serde_json"] }
lazy_static = "1.4.0"
minijinja = "0.32.1"
rand = "0.8"
regex = "1.10.0"
reqwest = "0.11.22"
serde = "1.0.188"
serde_json = "1.0.107"
sqlx = { version = "0.6.3", features = [
  "runtime-tokio-native-tls",
  "uuid",
  "json",
  "chrono",
  "sqlite",
  "offline",
  "migrate",
] }
tokio = { version = "1.33.0", features = ["full"] }
url = { version = "2.4.1", features = ["serde"] }
