[workspace]
resolver = "2"
members = ["src/*"]

[workspace.dependencies]
anyhow = "1.0.70"
minijinja = "0.32.0"
regex = "1.8.0"
serde = "1.0.160"
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "uuid", "json", "chrono", "sqlite", "offline", "migrate"] }
tokio = { version = "1.27.0", features = ["full"] }
# FIXME: this could probably be removed with some refactoring
twitch_api2 = { version = "0.6.1", features = ["twitch_oauth2", "helix", "reqwest", "time"] }
