[workspace]
resolver = "2"
members = ["src/*"]

[workspace.dependencies]
anyhow = "1.0.71"
chrono = "0.4.24"
fake = { git = "https://github.com/cksac/fake-rs", rev = "1c26a39", features = ["derive", "chrono", "serde_json"] }
lazy_static = "1.4.0"
minijinja = "0.32.1"
rand = "0.8"
regex = "1.8.1"
serde = "1.0.162"
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "uuid", "json", "chrono", "sqlite", "offline", "migrate"] }
tokio = { version = "1.28.1", features = ["full"] }
