[package]
name = "xddmod"
version = "0.1.0"
authors = ["Gian Lu <fusillicode@gmail.com>"]
edition = "2021"

[dependencies]
axum = "0.6.7"
hyper = { version = "0.14.24", features = ["full"] }
serde = "1.0.152"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "uuid", "json", "chrono", "sqlite", "offline"] }
tokio = { version = "1.25.0", features = ["full"] }
tower = "0.4.13"
twitch-irc = { version = "5.0.0", features = ["with-serde", "refreshing-token-native-tls"] }
