[package]
name = "xddmod"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2021"

[lib]
name = "xddmod"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
axum = "0.6.15"
chrono-tz = "0.8.1"
config = "0.13.3"
hyper = { version = "0.14.25", features = ["full"] }
minijinja = "0.31.0"
regex = "1.7.3"
reqwest = "0.11.16"
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tower = "0.4.13"
twitch_api2 = { version = "0.6.1", features = ["twitch_oauth2", "helix", "reqwest"] }
twitch-irc = { version = "5.0.0", features = ["with-serde", "refreshing-token-native-tls"] }
url = { version = "2.3.1", features = ["serde"] }
webbrowser = "0.8.9"
